// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-my-tickets.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.52.1";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}

// src/lib/mcp/tools/list-my-tickets.ts
var list_my_tickets_default = defineTool({
  name: "list_my_tickets",
  title: "List my lottery tickets",
  description: "List lottery tickets booked by the signed-in user. RLS scopes results to the caller.",
  inputSchema: {
    game_id: z.string().uuid().optional().describe("Optionally filter by lottery game id."),
    limit: z.number().int().min(1).max(200).optional().describe("Max tickets (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ game_id, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const sb = supabaseForUser(ctx);
    let q = sb.from("lottery_tickets").select("id,lottery_game_id,ticket_number,status,booked_at,rendered_ticket_url").eq("booked_by_user_id", ctx.getUserId()).order("booked_at", { ascending: false }).limit(limit ?? 50);
    if (game_id) q = q.eq("lottery_game_id", game_id);
    const { data, error } = await q;
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { tickets: data, count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/get-fc-balance.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
var get_fc_balance_default = defineTool2({
  name: "get_fc_balance",
  title: "Get Fortune Coin balance",
  description: "Get the signed-in user's Fortune Coin (FC) balance.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("fc_balances").select("balance,updated_at").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    const balance = data?.balance ?? 0;
    return {
      content: [{ type: "text", text: `Balance: ${balance} FC` }],
      structuredContent: { balance, updated_at: data?.updated_at ?? null }
    };
  }
});

// src/lib/mcp/tools/list-live-games.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_live_games_default = defineTool3({
  name: "list_live_games",
  title: "List live lottery games",
  description: "List currently open lottery games (online / booking_stopped / live). Returns id, title, ticket_price, game_date, status, total_tickets.",
  inputSchema: {
    limit: z2.number().int().min(1).max(100).optional().describe("Max games to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("lottery_games").select("id,title,ticket_price,game_date,status,total_tickets,headline,organising_group_name").in("status", ["online", "booking_stopped", "live"]).order("game_date", { ascending: true }).limit(limit ?? 25);
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { games: data }
    };
  }
});

// src/lib/mcp/tools/get-game-details.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^3.25.76";
var get_game_details_default = defineTool4({
  name: "get_game_details",
  title: "Get lottery game details",
  description: "Fetch full details for a single lottery game by id.",
  inputSchema: {
    game_id: z3.string().uuid().describe("Lottery game UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ game_id }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("lottery_games").select("*").eq("id", game_id).maybeSingle();
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data)
      return { content: [{ type: "text", text: "Game not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { game: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "bramvnherjbaiakwfvwb";
var mcp_default = defineMcp({
  name: "lottery-app-mcp",
  title: "Lottery App MCP",
  version: "0.1.0",
  instructions: "Tools for the signed-in user's lottery account. Use list_live_games to browse open games, get_game_details for a single game, list_my_tickets to see the caller's tickets, and get_fc_balance for their Fortune Coin balance.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_live_games_default, get_game_details_default, list_my_tickets_default, get_fc_balance_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
