// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://bramvnherjbaiakwfvwb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJyYW12bmhlcmpiYWlha3dmdndiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MTY5NzQsImV4cCI6MjA2OTA5Mjk3NH0.K_er4vhh8O7Q7rhJDvWqWTG9TVO-mc4D75ZnOjD2cgU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});